### PR TITLE
Add provider for LastFM

### PR DESCRIPTION
**Pull request by rafaelsq**

### CODE REVIEW

**Comment by tylerb** [comment]
It appears your package fails to build. Please resolve this:

```
# github.com/markbates/goth/providers/lastfm
providers/lastfm/lastfm_test.go:10: import "github.com/markbates/goth/providers/lastfm" while compiling that package (import cycle)
```

**Comment by rafaelsq** [comment]
:+1:

**Comment by rafaelsq** [comment]
@tylerb could you take another look!?

**Comment by tylerb** [comment]
LGTM

**Comment by tylerb** [comment]
Thanks!

**Pull request merged**
