### PR TITLE
Set "access_type=offline" to google provider as default

### PR DESCRIPTION
**Pull request by shiwano**
I set `access_type=offline` as default, referring to https://github.com/markbates/goth/pull/315#issuecomment-590389528

Related PRs: https://github.com/markbates/goth/pull/347 https://github.com/markbates/goth/pull/315

### CODE REVIEW

**Comment by pascalbros** [comment]
Any hope for this PR? Super useful!

**Comment by pascalbros** [comment]
@markbates would you wanna be my hero and merge this PR? Thanks. 🦸‍♂️
Cheers bud.

**Comment by pascalbros** [comment]
[](https://www.youtube.com/watch?v=id6l1nMqpvc)

**Comment by pascalbros** [comment]
[https://youtu.be/id6l1nMqpvc?t=25](https://youtu.be/id6l1nMqpvc?t=25)

**Comment by benja-M-1** [comment]
@markbates [is no longer maintaining this library](https://blog.gobuffalo.io/goth-needs-a-new-maintainer-626cd47ca37b)

Maybe @bentranter can help?

**Comment by uded** [comment]
OK, then who is actually maintaining this library? Is anyone doing that at all???

**Comment by techknowlogick** [comment]
I have reached out to Mark about volunteering to maintain goth, and hopefully will hear back.

**Comment by bentranter** [comment]
Hey folks, sorry, I've been struggling to find time to maintain this library over the last few months. I'll merge this, but hopefully @techknowlogick as assigned a maintainer by Mark, as I don't have permissions to add new maintainers.

**Comment by uded** [comment]
@bentranter thanks for the merge! But I do believe that #315 would be quite beneficial as well. Unfortunately, it has a conflict which would have to be resolved...

**Pull request merged**
