### PR TITLE
Added amazon,box,onedrive,salesforce and yammer providers

### PR DESCRIPTION
**Pull request by rakesh-eltropy**
Hi Markbates,

I have added providers for Amazon, Box, Onedrive, Salesforce and Yammer. I have tested them throughly and written the test cases as well. Kindly review and see if they can be merged to master. I would like to add refresh token also sometime by the next week end.

Thanks,
Rakesh Goyal

### CODE REVIEW

**Comment by rakesh-eltropy** [comment]
Gentle Reminder.

**Comment by markbates** [comment]
Sorry @rakesh-eltropy I didn't have a chance to look at this sooner.

Can I ask, what is the point of this line:

```go
var _ goth.Session = &Session{}
```

You seem to have it in all the session files.

**Comment by markbates** [comment]
@rakesh-eltropy never mind. dumb question. you're just checking the interface is met. i'm really tired. :)

This looks good! Thanks so much for the PR!

**Comment by rakesh-eltropy** [comment]
Thanks a lot mark. Thanks for the beautiful library.

**Pull request merged**
