### PR TITLE
Added Refresh Token/Expiry Date of Access Token for applicable providers

### PR DESCRIPTION
**Pull request by rakesh-eltropy**
Hi Mark,
I have Added Refresh Token/Expiry Date of Access Token for applicable providers. There is a change in provider interface where we have additional methods :

- RefreshToken(refreshToken string) (*oauth2.Token, error) //Get new access token based on the refresh token
- RefreshTokenAvailable()(bool) //Refresh token is provided by auth provider or not

I have implemented and tested these for all existing providers.

Kindly review and see if we can merge it to the master.

Thanks,
Rakesh Goyal

### CODE REVIEW

**Comment by bryanl** [comment]
@rakesh-eltropy thanks for the PR!

I have a few comments:

1. While `goth` wasn't 100% `golint` compliant before, in most cases, the godoc comments were correct. Could you update these?
2. A few of the files don't look they where formatted by `gofmt` (e.g `providers/digitalocean/digitalocean.go`)
3. Would `ExpiresAt` make more sense than `ExpiresIn`, since you are returning a time and not a duration?

**Comment by markbates** [comment]
Thanks @rakesh-eltropy for this PR! Awesome.

@bryanl thanks for taking the time to review it.

@rakesh-eltropy if you could update based on Bryan's comments that would be great!

**Comment by zmb3** [comment]
Does `RefreshToken()` have to be a method on the `Provider`?

It seems like we could pull that out into a package function so that each provider isn't forced to paste a copy of the same implementation.

Just thinking, if we try to keep providers lean and easy to implement we can expect to get more contributions.

**Comment by markbates** [comment]
@zmb3 I think that's a great idea. What does everyone else think?

**Comment by bryanl** [comment]
I think this is a good idea as well.

**Comment by markbates** [comment]
@rakesh-eltropy can you update to have a package level `RefreshToken()` function?

**Comment by rakesh-eltropy** [comment]
I feel implementation can change for different providers thats why I decided to keep it at provider level.

**Comment by rakesh-eltropy** [comment]
@bryanl thanks for taking the time to review it. I have incorporated your comments and goth is 100 % golint compliant now!

**Comment by markbates** [comment]
Can the implementation actually change for oauth2 refresh tokens between providers? I honestly don't know. Does anybody have any thoughts in this area? My gut says they should all be the same since they're all using the same oath2 package under the covers.

**Comment by markbates** [comment]
An alternative might be to create a `CommonProvider` that can be included into all provider implementations that would provide some default values and functions that could be overwritten on a per provider level if needed.

**Comment by rakesh-eltropy** [comment]
Also Mark, we would need tokenURL to make refresh token function work. Its not a great idea to ask user to pass tokenURL as it will be different for each provider and we want to keep it seamless for the library user.

**Comment by markbates** [comment]
@rakesh-eltropy i would assume you would take the provider as an argument to the `RefreshToken` function, which would solve that problem.

The biggest problem I see is that `RefreshToken` uses `p.config`, which is private, which would make a package level function not doable without adding a `Config()` function to the `Provider` implementation.

**Comment by markbates** [comment]
It doesn't sound like having a package level `RefreshToken` function makes sense, after thinking about it.

If no one has any other objections I'm going to merge this PR. Anyone?

**Comment by bryanl** [comment]
@markbates merge away

**Comment by bketelsen** [comment]
wow!

**Comment by rakesh-eltropy** [comment]
Thanks a ton Mark!

**Comment by markbates** [comment]
@rakesh-eltropy thank you!! This was a great PR!

**Pull request merged**
