### PR TITLE
Support for AzureAD

### PR DESCRIPTION
**Pull request by michalpristas**
Added support for Azure AD which uses microsoft online and azure ad graph API for fetching user.
Not included in this pack: support for microsoftonline version 2.0

### CODE REVIEW

**Comment by markbates** [comment]
I'm having trouble confirming this works, would you mind providing me with some instructions on how to set this up?

Thanks!

**Comment by michalpristas** [comment]
Do you have some azure app set-up? try this tutorial: https://auth0.com/docs/connections/enterprise/azure-active-directory/v2

**Comment by michalpristas** [comment]
i found an issue, please let me get back with an update

**Comment by markbates** [comment]
Thanks!

Any chance of adding support for "normal" logins though MS, not just Azure AD?

**Comment by michalpristas** [comment]
for sure I will look at it over the weekend. Another thing I want to do is in-memory session store so it works with localhost and verification of new providers gets easier

**Pull request merged**
