### PR TITLE
Support code formatting

### PR DESCRIPTION
**Pull request by qornanali**
Fix https://github.com/markbates/goth/issues/369

### CODE REVIEW

**Comment by techknowlogick** [comment]
This fails with windows due to bash, see more details here: #370

**Comment by qornanali** [comment]
> This fails with windows due to bash, see more details here: #370

yes, thank you for the clue!

**Review by bentranter — APPROVED** [review]
Thanks @techknowlogick and @qornanali!

**Comment by qornanali** [comment]
Hi @bentranter , would you mind labelling this PR with `hacktoberfest-accepted`?

**Pull request merged**
