### PR TITLE
twitter: add authenticate support

### PR DESCRIPTION
**Pull request by oov**
Hi, there!
I've added authentication support to Twitter provider.
Would you review my changes?

### CODE REVIEW

**Comment by markbates** [comment]
Can you please add some tests and perhaps an example of how to use this?

**Comment by oov** [comment]
Almost done!
Where shall I add an example?

**Comment by markbates** [comment]
There's an examples folder you can add an example to. Thanks.

**Comment by oov** [comment]
Thank you very much for your advice!
How does that look?

**Comment by markbates** [comment]
Thanks for the PR. It looks good. Thank you.

**Pull request merged**
