### PR TITLE
invalid example.go url in comments

### PR DESCRIPTION
**Pull request by tockn**
need `blob/master` to access `goth/examples/main.go`

### CODE REVIEW

**Comment by bentranter** [comment]
Looks like this is failing due to Go 1.7 and 1.8 not supporting the `type DefaultCredentials = Credentials` syntax in the new Google provider's `golang.org/x/oauth2/google` dependency, and is unrelated to this PR.

**Comment by tockn** [comment]
I see. what should I do?

**Comment by bentranter** [comment]
@tockn I'll fix it this weekend, no need to do anything for now.

**Comment by bentranter** [comment]
Ok, all fixed -- thanks @tockn for the contribution! 🎉

**Pull request merged**
