### PR TITLE
Added support for Microsoft Online

### PR DESCRIPTION
**Pull request by michalpristas**
- Added support for V2 of Microsoft Online OAuth2 API which can be used for Microsoft personal accounts.
- Small fixes in AzureAD provider
- Updated example suit

To test, application needs to be registered in [Application Registration Portal](https://apps.dev.microsoft.com/)

### CODE REVIEW

**Comment by markbates** [comment]
I keep hitting a strange error when trying to confirm. Everything looks good, but I keep hitting an error:  ` 'redirect_uri' value must be a valid absolute Uri.` 

Below is the URL of the page, and the `redirect_uri` looks well formed, and correct in it.

```
https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=fa009670-b57a-4b72-9943-09ba1c994032&redirect_uri=https%3A%2Flimitless-bayou-90422.herokuapp.com%2Fauth%2Fmicrosoftonline%2Fcallback&response_type=code&scope=offline_access+profile+openid&state=0v2CgwEfl1GZBM7tk1ggHbrRq7ANRe01ths_InikeKDs410ye-eRUq1ag_hI8BG8PrEL9E3p9fHHM-CPUfCkow%3D%3D
```

Here is the full error from the Microsoft page.

```
Sorry, but we’re having trouble signing you in.We received a bad request.

Additional technical information:
Correlation ID: 3e6e2538-e1af-4083-bc41-3e283d5cebe9
Timestamp: 2018-01-15 15:39:46Z
AADSTS90102: 'redirect_uri' value must be a valid absolute Uri.
```

Thoughts?

**Comment by michalpristas** [comment]
yes indeed. this message is correct but a bit misleading, it does not refer to any of the URI parameter in query path.
in the portal you need to edit manifest.
in XML you will find redirect_uri field which is set to []. 
you need to paste your "localhost/3000...." there and everything will be fine

**Comment by markbates** [comment]
This is no `redirect_uri` in the XML:

```xml
{
    "id": "f56193c3-7fcf-40a6-8709-f6e0ce10ad31",
    "addIns": [],
    "allowPublicClient": null,
    "appId": "fa009670-b57a-4b72-9943-09ba1c994032",
    "createdDateTime": "2018-01-10T16:45:24Z",
    "identifierUris": [],
    "informationalUrls": {
        "termsOfService": null,
        "privacy": null
    },
    "keyCredentials": [],
    "logoUrl": null,
    "logoutUrl": null,
    "name": "limitless-bayou-90422",
    "oauth2AllowImplicitFlow": true,
    "oauth2Permissions": [],
    "oauth2RequirePostResponse": false,
    "parentalControlSettings": {
        "countriesBlockedForMinors": [],
        "legalAgeGroupRule": "Allow"
    },
    "passwordCredentials": [
        {
            "customKeyIdentifier": null,
            "endDate": "2099-12-31T12:00:00Z",
            "keyId": "50df5bf5-3250-4b22-a6da-10a4e5074ed5",
            "startDate": "2018-01-15T15:13:53.3249987Z",
            "value": null,
            "createdOn": "2018-01-15T15:13:53.382589Z",
            "hint": "ezj"
        }
    ],
    "preAuthorizedApplications": [],
    "publisherDomain": "microsoftaccounts.onmicrosoft.com",
    "replyUrls": [
        "https://limitless-bayou-90422.herokuapp.com/auth/microsoftonline/callback"
    ],
    "requiredResourceAccess": [
        {
            "resourceAppId": "00000003-0000-0000-c000-000000000000",
            "resourceAccess": [
                {
                    "id": "7427e0e9-2fba-42fe-b0c0-848c9e6a8182",
                    "type": "Scope"
                },
                {
                    "id": "37f7f235-527c-4136-accd-4a02d197296e",
                    "type": "Scope"
                },
                {
                    "id": "14dad69e-099b-42c9-810b-d002981feec1",
                    "type": "Scope"
                }
            ]
        }
    ],
    "signInUrl": "https://limitless-bayou-90422.herokuapp.com",
    "tags": [
        "appModelVersion:2",
        "accessTokenVersion:1",
        "availableToOtherTenants:true",
        "supportsConvergence:true"
    ]
}
```

**Comment by michalpristas** [comment]
this is what i had in mind. and it looks correct
"replyUrls": [
        "https://limitless-bayou-90422.herokuapp.com/auth/microsoftonline/callback"
    ],

**Comment by markbates** [comment]
Yeah, everything looks correct. That's what's so weird.

**Comment by michalpristas** [comment]
URI in parameter is double encoded

**Comment by markbates** [comment]
Ok, I figured out the issue with the URI, apparently `path.Join` changes `https://` to `http:/`. Bizarre.

With that said, I'm getting returned back to the app on Heroku, but now I'm getting the following error:

```
2018-01-15T16:14:18.578460+00:00 app[web.1]: level=error msg="oauth2: server response missing access_token" content_type=text/html db=0s duration=1.06217892s human_size="0 B" method=GET path="/auth/microsoftonline/callback?code=Me4b6d441-bdd7-1e13-219d-c27c435000d7&state=aW73pa55exGDRnJl25tP4DzbNY8UG4W69yqyd6CUZw-ucrt2riJ-R6PUHxy5YcdjlVt4No2zTxUjkUGTACgUsg%3d%3d" request_id=24dd44f150-4392effe01 size=0 status=0
```

**Comment by michalpristas** [comment]
can you capture server response?

**Comment by markbates** [comment]
```
2018-01-15T16:27:39.570502+00:00 app[web.1]: level=error msg="oauth2: server response missing access_token" content_type=text/html db=0s duration=1.042068507s human_size="0 B" method=GET path="/auth/microsoftonline/callback?code=M0ed6a439-0ff0-1834-e221-f8fea616b728&state=_Zm7seXUYgWGM9NH2ucmbTNiiFtw0Pq9m0B-5pq32VXA2ixMjVfUEU-cjuEc4VcWQsbdVe-M-ek6QzIPQWlgrA%3d%3d" request_id=24dd44f150-66f4a53980 size=0 status=0
```

There is no request body coming back to the app.

**Comment by michalpristas** [comment]
this is weird, even with unsuccessful request it should respond at least with error message.
i don't like status 0 either

**Comment by markbates** [comment]
yeah, it's very weird.

**Comment by michalpristas** [comment]
code looks truncated as well

**Comment by markbates** [comment]
How long should it be? It looks long-ish to me:

/auth/microsoftonline/callback?code=M0ed6a439-0ff0-1834-e221-f8fea616b728&state=_Zm7seXUYgWGM9NH2ucmbTNiiFtw0Pq9m0B-5pq32VXA2ixMjVfUEU-cjuEc4VcWQsbdVe-M-ek6QzIPQWlgrA%3d%3d

**Comment by markbates** [comment]
There's no access_token in the URL. Perhaps there's a step missing in the implementation?

**Comment by michalpristas** [comment]
I tested this and verified in localhost. but i will recheck again

**Comment by michalpristas** [comment]
do you use example app or you have your own?

**Comment by markbates** [comment]
https://github.com/markbates/mstest

And I invited you to the Heroku app as well

**Comment by markbates** [comment]
I added a bunch of logging in the `CompleteUserAuth` method, here it is with the output. The `AccessToken` is always `""`.

```go
var CompleteUserAuth = func(res http.ResponseWriter, req *http.Request) (goth.User, error) {
	defer Logout(res, req)
	if !keySet && defaultStore == Store {
		fmt.Println("goth/gothic: no SESSION_SECRET environment variable is set. The default cookie store is not available and any calls will fail. Ignore this warning if you are using a different store.")
	}

	providerName, err := GetProviderName(req)
	fmt.Println("### providerName ->", providerName)
	fmt.Println("### err ->", err)
	if err != nil {
		return goth.User{}, err
	}

	provider, err := goth.GetProvider(providerName)
	fmt.Println("### provider ->", provider)
	fmt.Println("### err ->", err)
	if err != nil {
		return goth.User{}, err
	}

	value, err := getFromSession(providerName, req)
	fmt.Println("### value ->", value)
	fmt.Println("### err ->", err)
	if err != nil {
		return goth.User{}, err
	}

	sess, err := provider.UnmarshalSession(value)
	fmt.Println("### sess ->", sess)
	fmt.Println("### err ->", err)
	if err != nil {
		return goth.User{}, err
	}

	err = validateState(req, sess)
	fmt.Println("### err ->", err)
	if err != nil {
		return goth.User{}, err
	}

	user, err := provider.FetchUser(sess)
	fmt.Println("### user ->", user)
	fmt.Println("### err ->", err)
	if err == nil {
		// user can be found with existing session data
		return user, err
	}

	// get new token and retry fetch
	fmt.Println("### req.URL.Query() ->", req.URL.Query())
	x, err := sess.Authorize(provider, req.URL.Query())
	fmt.Println("### x ->", x)
	fmt.Println("### err ->", err)
	if err != nil {
		return goth.User{}, err
	}

	err = storeInSession(providerName, sess.Marshal(), req, res)
	fmt.Println("### err ->", err)

	if err != nil {
		return goth.User{}, err
	}

	gu, err := provider.FetchUser(sess)
	fmt.Println("### gu ->", gu)
	return gu, err
}
```

```
2018-01-15T16:47:31.258750+00:00 app[web.1]: ### providerName -> microsoftonline
2018-01-15T16:47:31.258751+00:00 app[web.1]: ### err -> <nil>
2018-01-15T16:47:31.258753+00:00 app[web.1]: ### provider -> &{fa009670-b57a-4b72-9943-09ba1c994032 ezjzLWOK55)*?xjlCCI277@ https://limitless-bayou-90422.herokuapp.com/auth/microsoftonline/callback <nil> 0xc4204355e0 microsoftonline }
2018-01-15T16:47:31.258754+00:00 app[web.1]: ### err -> <nil>
2018-01-15T16:47:31.258912+00:00 app[web.1]: ### value -> {"AuthURL":"https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=fa009670-b57a-4b72-9943-09ba1c994032\u0026redirect_uri=https%3A%2F%2Flimitless-bayou-90422.herokuapp.com%2Fauth%2Fmicrosoftonline%2Fcallback\u0026response_type=code\u0026scope=offline_access+profile+openid\u0026state=Lobx9oOdjV-BzWrkFqk_09F2e2DV4xwuKC7-uWavdwg698Zi8gVz7ck2tptreetNrfyVgBL9Roga4yJcswslHg%3D%3D","AccessToken":"","RefreshToken":"","TokenType":"","ExpiresAt":"0001-01-01T00:00:00Z"}
2018-01-15T16:47:31.258933+00:00 app[web.1]: ### err -> <nil>
2018-01-15T16:47:31.259041+00:00 app[web.1]: ### sess -> {"AuthURL":"https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=fa009670-b57a-4b72-9943-09ba1c994032\u0026redirect_uri=https%3A%2F%2Flimitless-bayou-90422.herokuapp.com%2Fauth%2Fmicrosoftonline%2Fcallback\u0026response_type=code\u0026scope=offline_access+profile+openid\u0026state=Lobx9oOdjV-BzWrkFqk_09F2e2DV4xwuKC7-uWavdwg698Zi8gVz7ck2tptreetNrfyVgBL9Roga4yJcswslHg%3D%3D","AccessToken":"","RefreshToken":"","TokenType":"","ExpiresAt":"0001-01-01T00:00:00Z"}
2018-01-15T16:47:31.259058+00:00 app[web.1]: ### err -> <nil>
2018-01-15T16:47:31.259095+00:00 app[web.1]: ### err -> <nil>
2018-01-15T16:47:31.259138+00:00 app[web.1]: ### user -> {map[] microsoftonline             0001-01-01 00:00:00 +0000 UTC}
2018-01-15T16:47:31.259156+00:00 app[web.1]: ### err -> microsoftonline cannot get user information without accessToken
2018-01-15T16:47:31.259188+00:00 app[web.1]: ### req.URL.Query() -> map[code:[M41d262d4-2e89-dcf7-b043-b6bb710252e5] state:[Lobx9oOdjV-BzWrkFqk_09F2e2DV4xwuKC7-uWavdwg698Zi8gVz7ck2tptreetNrfyVgBL9Roga4yJcswslHg==]]
2018-01-15T16:47:31.602379+00:00 app[web.1]: ### x -> 
```

**Comment by michalpristas** [comment]
i tested with postman and get this
`
{
    "refresh_token": "OAQABAAAAAABHh4kmS_aKT5XrjzxRAtHzVRGNSehCMqQEYy_PuCABf...K0EsEENiAA",
    "id_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ino0NHdNZEh1OHdLc3Vtcm..."
}
`

**Comment by michalpristas** [comment]
i think i know where the problem is

**Comment by markbates** [comment]
I redeployed, still same results.

**Comment by markbates** [comment]
When I've added support in other apps (in Ruby apps) I've set my Microsoft app to use these scopes: "offline_access", "profile", "openid" 

I've set this app exactly like the apps I have working else, with the only change being the Host (obviously). So I feel like the Microsoft side is correct, especially since the request is coming full circle back to my app.

I've tried setting those scopes manually by passing them into the `microsoftonline` provider, but still get the same error.

**Comment by michalpristas** [comment]
the thing is that when i use postman i get access token. 
i need to investigate on this, what is happening there

**Comment by michalpristas** [comment]
in logs i can see: level=error msg="securecookie: the value is too long"

**Comment by markbates** [comment]
That's a new error, at least. :) Is the Microsoft provider trying to store too much in the cookie perhaps?

**Comment by markbates** [comment]
the response url is different now too.

**Comment by michalpristas** [comment]
i added tokentype string, which is only "Bearer". 
so in result session is longer for "TokenType":"Bearer",
don;'t know how limit is set, but it might be the difference between other providers and this one

**Comment by michalpristas** [comment]
i hardcoded the Bearer token type. let's see if it helps

**Comment by markbates** [comment]
```
2018-01-15T18:00:17.977659+00:00 app[web.1]: level=info msg=/auth/microsoftonline content_type=text/html db=0s duration=2.29329ms human_size="401 B" method=GET path=/auth/microsoftonline request_id=24dd44f150-3419e4a9dd size=401 status=307
2018-01-15T18:00:20.215796+00:00 app[web.1]: ### providerName -> microsoftonline
2018-01-15T18:00:20.215808+00:00 app[web.1]: ### err -> <nil>
2018-01-15T18:00:20.215813+00:00 app[web.1]: ### provider -> &{fa009670-b57a-4b72-9943-09ba1c994032 ezjzLWOK55)*?xjlCCI277@ https://limitless-bayou-90422.herokuapp.com/auth/microsoftonline/callback <nil> 0xc420118930 microsoftonline }
2018-01-15T18:00:20.215814+00:00 app[web.1]: ### err -> <nil>
2018-01-15T18:00:20.215902+00:00 app[web.1]: ### value -> {"AuthURL":"https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=fa009670-b57a-4b72-9943-09ba1c994032\u0026redirect_uri=https%3A%2F%2Flimitless-bayou-90422.herokuapp.com%2Fauth%2Fmicrosoftonline%2Fcallback\u0026response_type=code\u0026scope=openid+mail.read\u0026state=Ydegz42aqXiDe7iN5loe5djO3E54lLl9_Her4yvSy-xXETCCBuGmyTPvIHx0SOt5nFiCEvxZgKVPVmfQGrnMfQ%3D%3D","AccessToken":"","RefreshToken":"","ExpiresAt":"0001-01-01T00:00:00Z"}
2018-01-15T18:00:20.215903+00:00 app[web.1]: ### err -> <nil>
2018-01-15T18:00:20.215965+00:00 app[web.1]: ### sess -> {"AuthURL":"https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=fa009670-b57a-4b72-9943-09ba1c994032\u0026redirect_uri=https%3A%2F%2Flimitless-bayou-90422.herokuapp.com%2Fauth%2Fmicrosoftonline%2Fcallback\u0026response_type=code\u0026scope=openid+mail.read\u0026state=Ydegz42aqXiDe7iN5loe5djO3E54lLl9_Her4yvSy-xXETCCBuGmyTPvIHx0SOt5nFiCEvxZgKVPVmfQGrnMfQ%3D%3D","AccessToken":"","RefreshToken":"","ExpiresAt":"0001-01-01T00:00:00Z"}
2018-01-15T18:00:20.215965+00:00 app[web.1]: ### err -> <nil>
2018-01-15T18:00:20.215984+00:00 app[web.1]: ### err -> <nil>
2018-01-15T18:00:20.216002+00:00 app[web.1]: ### user -> {map[] microsoftonline             0001-01-01 00:00:00 +0000 UTC}
2018-01-15T18:00:20.216040+00:00 app[web.1]: ### err -> microsoftonline cannot get user information without accessToken
2018-01-15T18:00:20.216044+00:00 app[web.1]: ### req.URL.Query() -> map[code:[M4d2f758e-601b-fc03-5a4b-02675005a665] state:[Ydegz42aqXiDe7iN5loe5djO3E54lLl9_Her4yvSy-xXETCCBuGmyTPvIHx0SOt5nFiCEvxZgKVPVmfQGrnMfQ==]]
2018-01-15T18:00:20.437207+00:00 app[web.1]: ### x -> EwA4A8l6BAAU7p9QDpi/D7xJLwsTgCg3TskyTaQAATfrNUDUmAZWXxxd/rPs73a5wGXQ4YIZ8F1EWmChhRR8KeADzjevnn4B+zP8g7gMpljmN4vFyhl8BjBh7Gf3LiA/3Klzbc0OIHhJG4LIx0UuGoWHYeMR9Ybc7CRUkjL+F/4fhSYrRdcSe46c7rLcFRYzabhEZqo/his2ChZfW6z9N6ek8WeRtAobmQf+vsLJ68kDy5RzIpbLoJpX1WTSCHPitW7EKerIJdM4VAc483FbBspILiZlGRZooY+Tm33cLoYVAJ0ZkNik5iAhQecQDAg5pUKxlyNL7GC6l5dwJ8e1LwdtC6KuaFaL1qMjFW6uMOMTLFTXEPR2zzWiEwYMx0gDZgAACP1Hh39f/Se3CAL2kU1fn1rKWtcnfKwiX16sWv7kxJYLlWNyzgcrqej1Xw1+Bobo0xWZGamL9d4PRhvkjOWzApMaQKnUuooH/GtQNhXVr+ts1nikFDRFCJmCACRO5BXADDmXATzgRyDHuzixxEL+DUL/IAe4MA3rUu9sd3q5r4VafmNrlwxw7/Xp2l/e3Pz/mIvfU6Fy8nffdw6QrIgKv96RfnBGB97HwnJbalg30gwzhJibIpCsxFUCON6AV+mJoeVNmMlIfGNteuZoC6Ola+kU2gsD1x3NQrb0nK4F5EnVcbweczl2jH7t1WSZhrcZEoiQggtPqtEdx5Bt9U5oTPlLwqZPvdjrdK/sXMTqzAR01A+iEJ1KVaTwxMC47KS+cG9/SdDiuXHMBC+0x8nWmIMyT3gaJ3Odg0J2g78gNk+8ujgEW2JsCEHLyheK9WN6bbDO1Y8DES1u3XZVyN4u3cE70DirXuiyuVdn8cwYfjj6hl/XynAP0CmvO6Ut3lTw0BAIKOVhMsSdcXuSRREjRDoACGNt2XyWLlHQwLGerZVBZaciEw3uJ9wlPRnXHn1DN23hOMcgIB3m5U7oLyczQ3BIsduNjD3jmUS+hkLg9/RzcNxS4MBLLMHsLMrh9WKM2WGfoXTo0qaxTTBtMWYEHyobwZ6nZY+0R833B15PwByYO02D2Y9gi6xhxSVHXT4O3BElMAI=
2018-01-15T18:00:20.437211+00:00 app[web.1]: ### err -> <nil>
2018-01-15T18:00:20.437339+00:00 app[web.1]: ### err -> <nil>
2018-01-15T18:00:20.486106+00:00 app[web.1]: ### gu -> {map[] microsoftonline          EwA4A8l6BAAU7p9QDpi/D7xJLwsTgCg3TskyTaQAATfrNUDUmAZWXxxd/rPs73a5wGXQ4YIZ8F1EWmChhRR8KeADzjevnn4B+zP8g7gMpljmN4vFyhl8BjBh7Gf3LiA/3Klzbc0OIHhJG4LIx0UuGoWHYeMR9Ybc7CRUkjL+F/4fhSYrRdcSe46c7rLcFRYzabhEZqo/his2ChZfW6z9N6ek8WeRtAobmQf+vsLJ68kDy5RzIpbLoJpX1WTSCHPitW7EKerIJdM4VAc483FbBspILiZlGRZooY+Tm33cLoYVAJ0ZkNik5iAhQecQDAg5pUKxlyNL7GC6l5dwJ8e1LwdtC6KuaFaL1qMjFW6uMOMTLFTXEPR2zzWiEwYMx0gDZgAACP1Hh39f/Se3CAL2kU1fn1rKWtcnfKwiX16sWv7kxJYLlWNyzgcrqej1Xw1+Bobo0xWZGamL9d4PRhvkjOWzApMaQKnUuooH/GtQNhXVr+ts1nikFDRFCJmCACRO5BXADDmXATzgRyDHuzixxEL+DUL/IAe4MA3rUu9sd3q5r4VafmNrlwxw7/Xp2l/e3Pz/mIvfU6Fy8nffdw6QrIgKv96RfnBGB97HwnJbalg30gwzhJibIpCsxFUCON6AV+mJoeVNmMlIfGNteuZoC6Ola+kU2gsD1x3NQrb0nK4F5EnVcbweczl2jH7t1WSZhrcZEoiQggtPqtEdx5Bt9U5oTPlLwqZPvdjrdK/sXMTqzAR01A+iEJ1KVaTwxMC47KS+cG9/SdDiuXHMBC+0x8nWmIMyT3gaJ3Odg0J2g78gNk+8ujgEW2JsCEHLyheK9WN6bbDO1Y8DES1u3XZVyN4u3cE70DirXuiyuVdn8cwYfjj6hl/XynAP0CmvO6Ut3lTw0BAIKOVhMsSdcXuSRREjRDoACGNt2XyWLlHQwLGerZVBZaciEw3uJ9wlPRnXHn1DN23hOMcgIB3m5U7oLyczQ3BIsduNjD3jmUS+hkLg9/RzcNxS4MBLLMHsLMrh9WKM2WGfoXTo0qaxTTBtMWYEHyobwZ6nZY+0R833B15PwByYO02D2Y9gi6xhxSVHXT4O3BElMAI=   2018-01-15 19:00:20.437106131 +0000 UTC m=+3732.210846764}
2018-01-15T18:00:20.487567+00:00 app[web.1]: level=info msg="/auth/microsoftonline/callback?code=M4d2f758e-601b-fc03-5a4b-02675005a665&state=Ydegz42aqXiDe7iN5loe5djO3E54lLl9_Her4yvSy-xXETCCBuGmyTPvIHx0SOt5nFiCEvxZgKVPVmfQGrnMfQ%3d%3d" content_type=text/html db=0s duration=272.602256ms human_size="0 B" method=GET path="/auth/microsoftonline/callback?code=M4d2f758e-601b-fc03-5a4b-02675005a665&state=Ydegz42aqXiDe7iN5loe5djO3E54lLl9_Her4yvSy-xXETCCBuGmyTPvIHx0SOt5nFiCEvxZgKVPVmfQGrnMfQ%3d%3d" request_id=24dd44f150-f4398ad3d5 size=0 status=0
2018-01-15T18:00:20.487608+00:00 app[web.1]: level=error msg="microsoftonline responded with a 401 trying to fetch user information" content_type=text/html db=0s duration=272.602256ms human_size="0 B" method=GET path="/auth/microsoftonline/callback?code=M4d2f758e-601b-fc03-5a4b-02675005a665&state=Ydegz42aqXiDe7iN5loe5djO3E54lLl9_Her4yvSy-xXETCCBuGmyTPvIHx0SOt5nFiCEvxZgKVPVmfQGrnMfQ%3d%3d" request_id=24dd44f150-f4398ad3d5 size=0 status=0
```

still nothing. different error this time. `microsoftonline responded with a 401 trying to fetch user information`

**Comment by markbates** [comment]
I also put the app into dev mode so the errors are displayed on the webpage, and we don't need to dig through logs.

**Comment by michalpristas** [comment]
Can you inject mail.read scope Im on the road and will be online in 20

**Comment by michalpristas** [comment]
TODO: update test not to use hardcoded values
get rid of panicing inside Marshal - use gzip when working with Store

**Comment by michalpristas** [comment]
@markbates ping?

**Comment by markbates** [comment]
@michalpristas sorry for the delay, this fell off my radar a bit. Thanks for you work on this!

**Pull request merged**
