### PR TITLE
Add support for Instagram 

### PR DESCRIPTION
**Pull request by sharadgana**
Added Instagram as provider

### CODE REVIEW

**Comment by markbates** [comment]
This looks good, but it looks like you deleted the .gitignore file Can you please restore it?

**Comment by sharadgana** [comment]
That was a gitignore that I created in my repo. I have now moved it to a global git ignore so that it doesn't get committed

**Comment by markbates** [comment]
No, that's the one I committed originally. Look at the history on the file. Can you please restore it and then I can merge this in. Thanks.

**Comment by sharadgana** [comment]
Done.

**Comment by markbates** [comment]
Looks good! Thanks!

**Comment by sharadgana** [comment]
I haven't updated the README yet

**Comment by markbates** [comment]
I just noticed that too. Can you update it and submit it? Thanks.

**Pull request merged**
